REM   Script: SQL_Cheat_Sheet_Basics
REM   Exercicios _ Fixação-

CREATE TABLE DEPARTAMENTO( 
    CODIGO INTEGER, 
    NOME VARCHAR(20), 
    ADDRESS VARCHAR(30) 
);

CREATE TABLE Funcionarios(   
   
    ID INTEGER PRIMARY KEY NOT NULL,   
    F_NAME VARCHAR(20),   
    L_NAME VARCHAR(20),   
    B_BORN DATE,  
    SALARIO DECIMAL (6,2),   
    DEP_ID INTEGER   
);

INSERT INTO DEPARTAMENTO VALUES 
(1, 'DP_EXATAS', 'SAO PAULO');

INSERT INTO DEPARTAMENTO VALUES 
(2, 'DP_CIENCIAS', 'RIO DE JANEIRO'), 
(3, 'DP_HUMANAS', 'DISTRITO FEDERAL');

INSERT INTO DEPARTAMENTO VALUES 
(2, 'DP_CIENCIAS', 'RIO DE JANEIRO'), 
(3, 'DP_HUMANAS', 'DISTRITO FEDERAL'), ;

INSERT INTO DEPARTAMENTO VALUES 
(2, 'DP_CIENCIAS', 'RIO DE JANEIRO'), 
(3, 'DP_HUMANAS', 'DISTRITO FEDERAL') ;

INSERT INTO DEPARTAMENTO VALUES 
(2, 'DP_CIENCIAS', 'RIO DE JANEIRO');

INSERT INTO DEPARTAMENTO VALUES 
3, 'DP_HUMANAS', 'DISTRITO FEDERAL');

INSERT INTO DEPARTAMENTO VALUES 
(3, 'DP_HUMANAS', 'DISTRITO FEDERAL');

SELECT * FROM DEPARTAMENTO;

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3), 
(2, 'Sara', 'Maria', '1997-06-30', 800.00);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3),(2, 'Sara', 'Maria', '1997-06-30', 800.00);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3),(2, 'Sara', 'Maria', '1997-06-30', 800.00);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3), 
(2, 'Sara', 'Maria', '1997-06-30', 800.00) ;

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3), 
(2, 'Sara', 'Maria', '1997-06-30', 800.00), 
(3, 'Italo', 'Ribeiro', '1998-12-30', 800.00) ;

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3), 
(2, 'Sara', 'Maria', '1997-06-30', 800.00), 
(3, 'Italo', 'Ribeiro', '1998-12-30', 800.00) ;

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3), 
(2, 'Sara', 'Maria', '1997-06-30', 800.00), 
(3, 'Italo', 'Ribeiro', '1998-12-30', 800.00) ;

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues',2018-03-04,666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','2018-03-04',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','1997',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues','1997',666.66,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600.00,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600.00,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600.00,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600.00,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', '1998-10-30',600,3);

INSERT INTO FUNCIONARIOS VALUES 
(1,'Pedro', 'Rodrigues', DATE '1998-10-30',600,3);

INSERT INTO FUNCIONARIOS VALUES 
(2,'Sara','Maria',DATE '1990-04-16', 700.00, 2), 
(3,'Italo', 'Ribeiro', DATE '1996-06-30',400.50,3);

INSERT INTO FUNCIONARIOS VALUES 
((2,'Sara','Maria',DATE '1990-04-16', 700.00, 2), 
(3,'Italo', 'Ribeiro', DATE '1996-06-30',400.50,3));

INSERT INTO FUNCIONARIOS VALUES 
((2,'Sara','Maria',DATE '1990-04-16', 700.00, 2), 
(3,'Italo', 'Ribeiro', DATE '1996-06-30',400.50,3) 
    );

INSERT INTO FUNCIONARIOS VALUES( 
(2,'Sara','Maria',DATE '1990-04-16', 700.00, 2), 
(3,'Italo', 'Ribeiro', DATE '1996-06-30',400.50,3) 
    );

INSERT INTO FUNCIONARIOS VALUES 
(2,'Sara','Maria',DATE '1990-04-16', 700.00, 2);

INSERT INTO FUNCIONARIOS VALUES 
(3,'Italo', 'Ribeiro', DATE '1996-06-30',400.50,3);

select * from departamentos;

select * from DEPARTAMENTO;

select * from FUNCIONARIOS;

INSERT INTO FUNCIONARIOS 
(4, 'Sofia', 'Sol', DATE'2005-04-30',2.000,1);

INSERT INTO FUNCIONARIOS values 
(4, 'Sofia', 'Sol', DATE'2005-04-30',2.000,1);

INSERT INTO FUNCIONARIOS values 
(5, 'Samara', 'Lemes', DATE'1997-03-13', 4.000,2);

select * from FUNCIONARIOS;

SELECT F_NAME, L_NAME FROM FUNCIONARIOS 
ORDER BY L_NAME;

INSERT INTO FUNCIONARIOS VALUES 
(5, 'Ana', 'Batista', DATE'1991-05-30',4);

INSERT INTO FUNCIONARIOS VALUES 
(5, 'Ana', 'Batista', DATE'1991-05-30',700.00,4);

INSERT INTO FUNCIONARIOS VALUES 
(5, 'Ana', 'Batista', DATE'1991-05-30',700.00, 4);

INSERT INTO FUNCIONARIOS VALUES 
(5,'Ana','Batista',DATE '1990-05-20', 900.00, 4);

select * from funcionarios;

INSERT INTO FUNCIONARIOS VALUES 
(6,'Ana', 'Batista', DATE '1970-05-07', 800.00,3);

SElECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 5;

SElECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS 
AS TOTAL_FUNCIONARIO FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS LIMIT 5;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS LIMIT=5;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE F_NAME LIMIT 5;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE F_NAME = '%S%' LIMIT 3;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT F_NAME FROM FUNCIONARIOS LIMIT 5;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT F_NAME FROM FUNCIONARIOS  
WHERE LIMIT 5;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT F_NAME FROM FUNCIONARIOS  
WHERE DEP_ID = 3 LIMIT 3;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT F_NAME FROM FUNCIONARIO 
LIMIT 3;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
LIMIT 0,2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
LIMIT 0,2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
LIMIT 0,2 ;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE F_NAME = 'S' LIMIT 0,2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 1 LIMIT 0,2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 1 LIMIT 0,2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 3 LIMIT 3;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS 
WHERE DEP_ID = 3 LIMIT 2;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

DELETE FROM FUNCIONARIOS  
WHERE F_NAME = 'SAMARA';

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

DELETE FROM FUNCIONARIOS  
WHERE F_NAME = 'SAMARA';

SELECT F_NAME FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

DELETE FROM FUNCIONARIOS  
WHERE F_NAME IN 'SAMARA';

SELECT F_NAME FROM FUNCIONARIOS;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

DELETE FROM FUNCIONARIOS  
WHERE DEP_ID = 1;

SELECT * FROM FUNCIONARIOS;

SElECT F_NAME FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT(ID) FROM FUNCIONARIOS;

SELECT DISTINCT DEP_ID FROM FUNCIONARIOS;

UPDATE FUNCIONARIOS SET F_NAME = 'OPERADOR' 
WHERE F_NAME = 'Sofia';

SELECT F_NAME FROM FUNCIONARIOS;

DELETE FROM FUNCIONARIOS  
WHERE DEP_ID = 1;

SELECT * FROM FUNCIONARIOS;

