REM   Script: Treinamento SQL
REM   Exercicios fixação.

CREATE TABLE DEPARTAMENTO( 
    CODIGO INTEGER, 
    NOME VARCHAR(20), 
    ADDRESS VARCHAR(30) 
);

CREATE TABLE Funcionarios(   
   
    ID INTEGER PRIMARY KEY NOT NULL,   
    F_NAME VARCHAR(20),   
    L_NAME VARCHAR(20),   
    B_BORN DATE,  
    SALARIO DECIMAL (6,2),   
    DEP_ID INTEGER   
);

INSERT INTO DEPARTAMENTO VALUES 
(01, 'CIENCIAS_DP', 'SAO PAULO');

INSERT INTO DEPARTAMENTO VALUES 
(02, 'EXATAS_DP', 'RIO DE JANEIRO');

INSERT INTO DEPARTAMENTO VALUES 
(03, 'HUMANAS', 'DISTRITO FEDERAL');

SELECT * FROM DEPARTAMENTOS;

SELECT * FROM DEPARTAMENTO;

(01, 'Sara', 'Maria', DATE '20-03-2005', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
    (01, 'Sara', 'Maria', DATE '1998-03-30', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
    (01, 'Sara', 'Maria', DATE '20-03-2005', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
    (01, 'Sara', 'Maria', DATE '1998-03-30', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
(01, 'Sara', 'Maria', DATE '1998-03-30', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
(01, 'Sara', 'Maria', DATE '1998-03-30', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
(01, 'Sara', 'Maria', DATE'1998-03-30', 699.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
(01, 'Sara', 'Maria', DATE'1998-03-30', 699.00, 1);

SELECT * FROM FUNCIONARIOS;

INSERT INTO FUNCIONARIOS VALUES 
(02, 'Ana', 'Maria', DATE'1997-03-30', 700.00, 3);

INSERT INTO FUNCIONARIOS VALUES 
(03, 'Bruno', 'Fernandas', DATE'1980-03-30', 1000.00, 3);

INSERT INTO FUNCIONARIOS VALUES 
(04, 'Alex', 'Ribeiro', DATE'1989-05-31', 2000.00, 1);

INSERT INTO FUNCIONARIOS VALUES 
(05, 'Gabi', 'Gonçalves', DATE'1978-07-11', 3000.00, 2);

INSERT INTO FUNCIONARIOS VALUES 
(06, 'Julia', 'Bianz', DATE'1979-05-11', 200.00, 3);

INSERT INTO FUNCIONARIOS VALUES 
(07, 'Rodrigo', 'Lopez', DATE'1986-06-18', 100.00, 2);

SELECT * FROM FUNCIONARIOS;

SELECT AVG(SALARY) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO, F_NAME) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS 
SELECT F_NAME;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGHT(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGTH(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGTH(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT UCASE(F_NAME) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGTH(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT UCASE(F_NAME) FROM FUNCIONARIOS;

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGTH(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT UCASE(F_NAME) FROM FUNCIONARIOS;

SELECT DISTINCT(UCASE(F_NAME) FROM FUNCIONARIOS);

SELECT AVG(SALARIO) FROM FUNCIONARIOS;

SELECT COUNT(F_NAME) FROM FUNCIONARIOS 
WHERE DEP_ID = 3;

SELECT COUNT (F_NAME) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT MIN(SALARIO) FROM FUNCIONARIOS;

SELECT MAX(SALARIO) FROM FUNCIONARIOS;

SELECT ROUND(SALARIO) FROM FUNCIONARIOS;

SELECT LENGTH(F_NAME) FROM FUNCIONARIOS 
WHERE ID = 1;

SELECT UCASE(F_NAME) FROM FUNCIONARIOS;

SELECT DISTINCT(UCASE(F_NAME)) FROM FUNCIONARIOS;

